# Build-time build recipe configuration for the FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# this file contains sections that describe hardware designs that /can/ be built.
# edit config_build.yaml to actually "turn on" a config to be built when you run
# buildafi

###########
# Schema:
###########
# <NAME>:
#    DESIGN: <>
#    TARGET_CONFIG: <>
#    PLATFORM_CONFIG: Config
#    deploy_triplet: null
#    post_build_hook: null
#    metasim_customruntimeconfig: "path to custom runtime config for metasims"
#    bit_builder_recipe:
#    # OPTIONAL: overrides for bit builder recipe
#    # Arg structure should be identical to the args given
#    # in the base_recipe.
#    #bit_builder_arg_overrides:
#    #  <ARG>: <OVERRIDE>

# ASPLOS 2023: Build recipes for Rocket-based designs, constrained to 90MHz for resource utilization
coverage_rocket_48:
    DESIGN: FireSim
    TARGET_CONFIG: CCW48_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_32:
    DESIGN: FireSim
    TARGET_CONFIG: CCW32_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_16:
    DESIGN: FireSim
    TARGET_CONFIG: CCW16_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_8:
    DESIGN: FireSim
    TARGET_CONFIG: CCW8_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_4:
    DESIGN: FireSim
    TARGET_CONFIG: CCW4_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_2:
    DESIGN: FireSim
    TARGET_CONFIG: CCW2_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_1:
    DESIGN: FireSim
    TARGET_CONFIG: CCW1_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_baseline:
    DESIGN: FireSim
    TARGET_CONFIG: WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F90MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

# constrained to 140MHz in order to measure f_max
coverage_rocket_48_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW48_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_32_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW32_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_16_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW16_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_8_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW8_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_4_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW4_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_2_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW2_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_1_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: CCW1_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_rocket_baseline_f_max:
    DESIGN: FireSim
    TARGET_CONFIG: WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.QuadRocketConfig
    PLATFORM_CONFIG: WithAutoILA_F140MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

# ASPLOS 2023: Build recipes for Boom-based designs, unfortunately newer Vivado versions segfault on instrumented BOOM builds
coverage_boom_48:
    DESIGN: FireSim
    TARGET_CONFIG: CCW48_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_32:
    DESIGN: FireSim
    TARGET_CONFIG: CCW32_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_16:
    DESIGN: FireSim
    TARGET_CONFIG: CCW16_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_8:
    DESIGN: FireSim
    TARGET_CONFIG: CCW8_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_4:
    DESIGN: FireSim
    TARGET_CONFIG: CCW4_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_2:
    DESIGN: FireSim
    TARGET_CONFIG: CCW2_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_1:
    DESIGN: FireSim
    TARGET_CONFIG: CCW1_WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

coverage_boom_baseline:
    DESIGN: FireSim
    TARGET_CONFIG: WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard.LargeBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_Area_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

